### ISSUE TITLE
Erro ao criar o app - npm ERC! Code ENOLOCAL

### ISSUE THREAD

**Issue by alissonsuassuna** [nullstack/create-nullstack-app#10]
Ao tentar criar um projeto com nullstack executando o comando orientado pela documentação:

`npx create-nullstack-app project-name`

O terminal me deu o seguinte erro:

npm ERR! code ENOLOCAL
npm ERC! Could not install form "User/AppData/Roamin/npm-cache/_npx/8952" as it does not contain a package.json file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\usuario\AppDatazRoamin\npm-cache\_logs2021-03-13T21_03_45_892Z-debug-lof
install for [ 'create-nullstack-app@latest' ] failed with code 1

**Comment by Mortaro** [comment]
Yay 💖 

Obrigado pros 2 (^人^)
